export const QUERY_VIDEO_RECOMMENDED = '/video/recommended'
export const QUERY_USER_FRIENDS = '/user/friends'
export const QUERY_VIDEO_COMMENTS = '/video/comments'
export const QUERY_USER_VIDEOS = '/user/video_list'
export const QUERY_SHOP_RECOMMEND = '/shop/recommended'
export const QUERY_POST_RECOMMEND = '/post/recommended'